su_filter_srcs = files(
    'subfilt.cpp',
    #'succfilt.c',
    #'sudeghost.c',
    #'sudipfilt.c',
    'sufilter.cpp',
    'sufrac.cpp',
    #'sufwatrim.c',
    #'suk1k2filter.c',
    #'sukfilter.c',
    #'sukfrac.c',
    #'sulfaf.c',
    'sumedian.cpp',
    'suminphase.cpp',
    'suphase.cpp',
    #'susmgauss2.c',
    #'susvdfilt.c',
    'sutvband.cpp',
)

su_main_srcs += su_filter_srcs
