su_filter_srcs = files(
    'subfilt.c',
    #'succfilt.c',
    #'sudeghost.c',
    #'sudipfilt.c',
    #'sufilter.c',
    #'sufrac.c',
    #'sufwatrim.c',
    #'suk1k2filter.c',
    #'sukfilter.c',
    #'sukfrac.c',
    #'sulfaf.c',
    #'sumedian.c',
    #'suminphase.c',
    #'suphase.c',
    #'susmgauss2.c',
    #'susvdfilt.c',
    #'sutvband.c',
)

su_main_srcs += su_filter_srcs
