synthetics_srcs = files(
    'sufdmod1.cpp',
    'sufdmod2.cpp',
    'sufdmod2_pml.cpp',
    'suea2df.cpp',
    'suremac2d.cpp',
    'sufctanismod.cpp',
    'suremel2dan.cpp',
    'sugoupillaud.cpp',
    'sugoupillaudpo.cpp',
    'suimp2d.cpp',
    'suimp3d.cpp',
    'sukdsyn2d.cpp',
    'susyncz.cpp',
    'susynlv.cpp',
    'susynlvcw.cpp',
    'susynlvfti.cpp',
    'susynvxz.cpp',
    'susynvxzcs.cpp',
    'suvibro.cpp',
)

su_main_srcs += synthetics_srcs