synthetics_srcs = files(
    'sugoupillaud.cpp',
    'sugoupillaudpo.cpp',
    'suimp2d.cpp',
    'suimp3d.cpp',
    'susyncz.cpp',
    'suvibro.cpp',
    'sukdsyn2d.cpp',
    'susynlv.cpp',
    'susynlvcw.cpp',
    'susynlvfti.cpp',
    'susynvxz.cpp',
    'susynvxzcs.cpp',
)

su_main_srcs += synthetics_srcs