/* Copyright (c) Colorado School of Mines, 2011.*/
/* All rights reserved.		       */

/* SUEA2DF: $Revision: 1.30 $ ; $Date: 2015/06/02 20:15:23 $		 */

#include "su.h"
#include "segy.h"
/*********************** self documentation **********************/
#if 0 /* the sdoc of the program, which is not part of the library */
char *sdoc[] = {
"									",
" SUEA2DF - SU version of (an)elastic anisotropic 2D finite difference 	",
"		forward modeling, 4th order in space			",
"									",
" suea2df > outfile c11file= c55file  [optional parameters]		",
"									",
" Required Parameters:							",
" c11file=c11_file	c11 voigt elasticity parameter filename		",
" c55file=c55_file	c55 voigt elasticity parameter filename		",
"									",
" Optional Parameters:							",
" rhofile=rho_file	density filename				",
"			(if rhofile is not set, rho=1000 is assumed)	",
" Anisotropy parameters:						",
" aniso=0	 	 =1 - include anisotropy parameters		",
" mode=0		=0 output particle velocity, =1 output stresses ",
"			(snapshots only)				",
"									",
" ... the next 3 parameters become active only when aniso=1....		",
" c13file=c13_file	c13 voigt elasticity parameter filename		",
" c33file=c33_file	c33 voigt elasticity parameter filename		",
" c15file=c15_file	c15 voigt elasticity parameter filename		",
" c35file=c35_file	c35 voigt elasticity parameter filename		",
"									",
" Attenuation parameters:						 ",
" qsw=0		 switch to include attenuation =1 - include		",
" ... the next parameter becomes active only when qsw=1....	     	",
" qfile=Q_file	  Q parameter filename	    				",
"									",
" dt=0.001		time sampling interval (s)			",
" ft=0.0 		first time (s)				 	",
" lt=1.0 		last time (s)					",
"									",
" nx=200		number of values in slow (x-direction)		",
" dx=10.0	 	spatial sampling interval (m) x-coor		",
" fx=-1000		first x coor (m)				",
"									",
" nz=100		number of values in fast (z)-dimension		",
" dz=dx			spatial sampling interval (m) z-coor		",
" fz=0			firstz coor (m)  				",
"									",
" Source parameters:							",
" sx=0			source x position (m)				",
" sz=500		source location (m)  				",
" stype='p'		source type					",
"			  p: P-wave					",
"			  v: velocity					",
"			 pw: P plane-wave				",
" sang=0		for stype='pw': plane wave angle		",
" wtype='dg'		wave type					",
" 			 dg: Gaussian derivative 			",
" 			 ga: Gaussian		 			",
" 			 ri: Ricker					",
" 			 sp: spike, sp2: double spike   		",
" ts=0.05		source duration (s)				",
" favg=50		source average frequency			",
"									",
" Attenuation parameters:						",
" qsw=0		 	switch to include attenuation =1 - include	",
"									",
" Boundary condition parameters:					",
" bc=10,10,10,10 	Top,left,bottom,right boundary condition	",
" 			=0 none						",
" 			=1 symmetry 					",
" 			=2 free surface (top only)			",
" 			>2 absorbing (value indicates width of absorbing",
"			layer	 					",
" bc_a=0.95;		bc initial taper value for absorbing boundary  ",
" bc_r=0.;		bc exponential factor for absorbing boundary  	",
" 			variables are scaled by bc_a*pow(i,-bc_r)	",
"									",
" Optional output parameters:						",
" sofile=		name of source file				",
" snfile=		name of file containing for snapshots		",
" snaptime=		times of snapshots i.e. snaptime=0.1,0.2,0.3	",
"									",
" vsx=			x coordinate of vertical line of seismograms	",
" hsz=			z coordinate of horizontal line of seismograms	",
" vrslfile=\"vsp.su\"	output file for vertical line of seismograms[nz][nt]",
" hsfile=\"hs.su\" 	output file for horizontal line of seismograms[nx][nt]",
" tsw=0		 	switch to use shear stress only in non-fluid	",
"			media - may help reduce dispersion tsw=1. If	",
"			tsw=0 then standard calculation	  		",
" verbose=0		=1 to print progress on screen			",
"									",
" Notes:								",
" 1) The outfile contains information generated by the input parameters,",
"    such as memory allocation, stability, etc. If your input file does	",
"    not work, check this file first.					",
"									",
" The model is specified as binary files of stiffness parameters and    ",
" densities. These may be created any way the user desires. The program ",
" unif2 or makevel may be used to generate densities, and the program	",
" unif2aniso may be used to generate the stiffnesses. You will need to	",
" transpose these files (stiffnesses and densities), as the input	",
" format for suea2df assumes that the fast dimesion is the horizontal or ",
" the x-dimension. You may do this via					",
" 									",
"  transp n1=nz < c11_file > transp_c11_file				",
"									",
" If aniso=1 then the program will expect the additional stiffnesss files.",
"									",
" If qsw=1 unif2anis can be used to generate the Q values on a grid	",
" These value also need to be transposed, as with the stiffnesses.	",
"									",
"Output files (always generated)					",
"	hsfile								",
"	vrslfile							",
"	hsfile.chd - header for hsfile					",
"	vrslfile.chd - header for vrslfile				",
"	hsfile.mod - model file						",
"									",
" Output files (if requested)						",
"	sofile - ascii source file					",
"	snfile  - su format snapshots file				",
"									",
" Caveat:								",
" A common error in using this program is to compute stiffnesses with	",
" a specified density, but forget to specify this density as the rhofile.",
NULL};
#endif


/* 
 * Credits: UU GEOPHY Chris Juhlin 15 May 1999
 * Copyright (c) Uppsala University, 1998.
 * All rights reserved.			
 * Parts of program use Seismic Unix Package - CSM
 * Changes - C. Juhlin
 *
 * 1. Fixed upgrading of stresses. There was an error in the coding for
 * the Tzz term, c15 was being used instead of c35. This only caused
 * problems for dipping anisotropic layers
 *
 * 2. Added some header information for hutput of snapshots.
 *
 * 3. 2001-01-30: Added option to set absorbing bc constants bc_a and bc_r 
 *
 * 4. 2001-02-23: Corrected bug in outputting model boundaries to standard
 * output in 
 * routine get_econst
 *
 * 5. 2001-04-26: Added option for updating velocities to only use 
 * shear stress if material is non-fluid, this appears to reduce dispersion at 
 * near grazing angles for fluid-solid boundary. Set tsw=1 to invoke
 *
 * 6. 2001-05-14: Changed loop in free-surface boundary condition for velocties
 * Thanks goes to Mike Holzrichter for pointing out this problem and the wrong
 * scaling factor in the updating.
 *
 * 7. 2001-05-16: Changed set_layers function to avoid negative indexing.
 * Thanks goes to Mike Holzrichter for pointing out this problem
 *
 * 8. 2001-05-17: Modified make_seis to take into account VSP geometry
 * correctly and not store unnecessary data.
 *
 * 9. 2001-08-21: Fixed set_layers so mode fills properly in depth. Earlier
 * versions were accessing incorrect array locations at last defined depth.
 *
 * 10. 2003-04-21: Fixed boundary conditions.
 *
 * 11. 2003-05-02: Extended the model area by half the grid spacing on the RHS.
 * This makes the model area symmetric allowing a plane wave source to be
 * introduced into the model (stype=pw). The w, txx and tzz grids contain now
 * one more column than the u and txz grids.
 *
 * 12. 2003-05-02: Added routines to allow plane waves to be introduced at a 
 * specified angle (sang) into the model with functions add_pw_source_V and
 * add_pw_source_S.
 *
 * 13. 15 Oct 2005 -- tossed all the model building stuff. Read models
 *	from binary files made by  unif2aniso (CWP:John Stockwell)
 *
 * 14. 25 Feb 2008 -- Fixed attenutation option (qsw=1) so that Q values are
 *	from binary files made by makevel or similar program
 *
 * 15. 1 April 2010 -- Changed free surface velocity BC back to original.
 *	Someone had changed the scaling factor from 2.0 to 0.5 in fs4v_bc_top
 *
 * Algorithm based on Juhlin (1995, Geophys. Prosp.)
 *	and Levander (1988, Geophysics)
 * Attenuation included as in Graves (1996, BSSA)
 *
 */

/**************** end self doc ********************************/

#define	F1	1.125
#define	F2	-0.04166667

static int get_source(float dt, float ts, float favg, char *wtype, float *source)
{
	int i,ns; float t,x,xx,pi2;
	i=0; t=0; pi2=PI*PI;
	ns=NINT(ts/dt)+1;
	while (i<ns) {
	  if(strcmp(wtype,"ri")==0){ /*Ricker*/
		x=favg*(t-ts/2);xx=x*x;
		source[i]=(1-2*pi2*(xx))*exp(-pi2*xx);
	  } 							  
	  if(strcmp(wtype,"dg")==0){ /*Derivative of Gaussian*/
		x=-4*favg*favg*pi2/log(0.1);
		source[i]=-2*pi2*(t-ts/2)*exp(-x*(t-ts/2)*(t-ts/2));
	  } 							  
	  if(strcmp(wtype,"ga")==0){ /*Gaussian favg is 10% level for fmax*/
		x=-favg*favg*pi2/log(0.1);
		source[i]=exp(-x*(t-ts/2)*(t-ts/2));
	  } 							  
	  if(strcmp(wtype,"sp")==0){ /*spike*/
		source[0]=1;
	  } 						
	  if(strcmp(wtype,"sp2")==0){ /*spike*/
		source[0]=1;
		source[1]=1;
	  } 						
 	  /*warn("%d %f %f\n",i,t,source[i]);*/
	  t=t+dt; i=i+1;
	}
	return(i);
}

static void update_vel(int ifx, int ilx, int jfz, int jlz,
	float **u, float **w, float **txx, float **tzz, float **txz,
	float **rho, float **c55, float dtx, float dtz)
{
	int i,j;
	float dtxx=0,dtzz=0,dtxz=0,dtzx=0;
	 	for (j=jfz; j<=jlz; ++j) {
	 	  for (i=ifx; i<=ilx; ++i) {
	 		dtxx = F1*(txx[j][i+1]-txx[j][i])
		 +F2*(txx[j][i+2]-txx[j][i-1]);
		dtxz = F1*(txz[j+1][i]-txz[j][i])
	 		+F2*(txz[j+2][i]-txz[j-1][i]);
			u[j][i] = u[j][i] + ( dtx*dtxx + dtz*dtxz ) * rho[j][i];
	 	  }
	 	  for (i=ifx; i<=ilx+1; ++i) {
			dtzz = F1*(tzz[j][i]-tzz[j-1][i])
	 		+F2*(tzz[j+1][i]-tzz[j-2][i]);
	 		dtzx = F1*(txz[j][i]-txz[j][i-1])
	 		+F2*(txz[j][i+1]-txz[j][i-2]);
	 		w[j][i] = w[j][i] + ( dtx*dtzx + dtz*dtzz ) * rho[j][i];
	 	  }
	 	}
}
static void update_vel_tsw(int ifx, int ilx, int jfz, int jlz,
	float **u, float **w, float **txx, float **tzz, float **txz,
	float **rho, float **c55, float dtx, float dtz)
{
	int i,j;
	float dtxx=0,dtzz=0,dtxz=0,dtzx=0;
	 	for (j=jfz; j<=jlz; ++j) {
	 	  for (i=ifx; i<=ilx; ++i) {
	 		dtxx = F1*(txx[j][i+1]-txx[j][i])
		 +F2*(txx[j][i+2]-txx[j][i-1]);
/*  		Only use 4th order shear stress derivatives if material is non-fluid, otherwise problems occur at grazing angles near fluid-solid boundary */
	 		if(c55[j][i]>0) { 
		 dtxz = F1*(txz[j+1][i]-txz[j][i])
	 		+F2*(txz[j+2][i]-txz[j-1][i]);
		}
		else{
		 dtxz = (txz[j+1][i]-txz[j][i]);
		}
	 		u[j][i] = u[j][i] + ( dtx*dtxx + dtz*dtxz ) * rho[j][i];
	 	  }
	 	  for (i=ifx; i<=ilx+1; ++i) {
	 		dtzz = F1*(tzz[j][i]-tzz[j-1][i])
	 		+F2*(tzz[j+1][i]-tzz[j-2][i]);
/*  		Only use 4th order shear stress derivatives if material is non-fluid, otherwise problems occur at grazing angles near fluid-solid boundary */
	 		if(c55[j][i]>0) { 
	 		dtzx = F1*(txz[j][i]-txz[j][i-1])
	 		+F2*(txz[j][i+1]-txz[j][i-2]);
		}
		else{
	 		dtzx = (txz[j][i]-txz[j][i-1]);
		}
	 		w[j][i] = w[j][i] + ( dtx*dtzx + dtz*dtzz ) * rho[j][i];
	 	  }
	 	}
}


static void update_stress_iso(int ifx, int ilx, int jfz, int jlz,
	float **u, float **w, float **txx, float **tzz, float **txz,
	float **c11, float **c55, float dtx, float dtz)
{
	int i,j;
	float dux,duz,dwz,dwx;
	 	for (j=jfz; j<=jlz; ++j) {
	 	  for (i=ifx; i<=ilx+1; ++i) {
	 		dwz = F1*(w[j+1][i]-w[j][i])
	 		+F2*(w[j+2][i]-w[j-1][i]);
	 		dux = F1*(u[j][i]-u[j][i-1])
	 		+F2*(u[j][i+1]-u[j][i-2]);
	 		txx[j][i] = txx[j][i] +
	 		c11[j][i]*dtx*dux + (c11[j][i]-2*c55[j][i])*dtz*dwz;
	 		tzz[j][i] = tzz[j][i] +
	 		c11[j][i]*dtz*dwz + (c11[j][i]-2*c55[j][i])*dtx*dux;
	 	  }
	 	  for (i=ifx; i<=ilx; ++i) {
	 		dwx = F1*(w[j][i+1]-w[j][i])
		 +F2*(w[j][i+2]-w[j][i-1]);
	 		duz = F1*(u[j][i]-u[j-1][i])
	 		+F2*(u[j+1][i]-u[j-2][i]);
	 		txz[j][i] = txz[j][i] +
	 		c55[j][i]*(dtz*duz + dtx*dwx);
	 	  }
	 	}
}

static void update_stress_ani(int ifx, int ilx, int jfz, int jlz,
	float **u, float **w, float **txx, float **tzz, float **txz,
	float **c11, float **c55, float **c33, float **c13, 
	float **c15, float **c35, float dtx, float dtz)
{
	int i,j;
	float dux,duz,dwz,dwx;

 	for (j=jfz; j<=jlz; ++j) {
		for (i=ifx; i<=ilx; ++i) {

			dwx = F1*(w[j][i+1]-w[j][i])
				+F2*(w[j][i+2]-w[j][i-1]);

			duz = F1*(u[j][i]-u[j-1][i])
	 					+F2*(u[j+1][i]-u[j-2][i]);

	 				dwz = F1*(w[j+1][i]-w[j][i])
	 					+F2*(w[j+2][i]-w[j-1][i]);

					dux = F1*(u[j][i]-u[j][i-1])
			 		+F2*(u[j][i+1]-u[j][i-2]);

			txx[j][i] = txx[j][i] 
					+ c11[j][i]*dtx*dux 
					+ c13[j][i]*dtz*dwz 
					+ c15[j][i]*(dtz*duz + dtx*dwx);

					tzz[j][i] = tzz[j][i] 
					+ c33[j][i]*dtz*dwz 
					+ c13[j][i]*dtx*dux 
					+ c35[j][i]*(dtz*duz + dtx*dwx); 

			txz[j][i] = txz[j][i] 
					+ c15[j][i]*dtx*dux 
					+ c35[j][i]*dtz*dwz 
					+ c55[j][i]*(dtz*duz + dtx*dwx);
	 	  	}
		i=ilx+1;

		dwx = F1*(w[j][i+1]-w[j][i])
		 		+ F2*(w[j][i+2]-w[j][i-1]);

		duz = F1*(u[j][i]-u[j-1][i])
	 				+ F2*(u[j+1][i]-u[j-2][i]);

	 			dwz = F1*(w[j+1][i]-w[j][i])
			+ F2*(w[j+2][i]-w[j-1][i]);

	 			dux = F1*(u[j][i]-u[j][i-1])
			+ F2*(u[j][i+1]-u[j][i-2]);

		txx[j][i] = txx[j][i] 
			+ c11[j][i]*dtx*dux 
			+ c13[j][i]*dtz*dwz 
			+ c15[j][i]*(dtz*duz + dtx*dwx);

	 			tzz[j][i] = tzz[j][i] 
			+ c33[j][i]*dtz*dwz 
			+ c13[j][i]*dtx*dux 
			+ c35[j][i]*(dtz*duz + dtx*dwx); 
	}
}


static void add_p_source(float **txx, float **tzz, float amp, int i, int j)
{
	txx[j][i] = txx[j][i] + amp;
	tzz[j][i] = tzz[j][i] + amp;
}

static void add_v_source(float **u, float **w, float amp, int i, int j)
{
	w[j][i] = w[j][i] + amp*0.000001;
}


static void add_pw_source_V(float **u, float **w, float **txx, float **tzz, 
	float **txz, float **c11, float **c55, float *a, float sang,
	int il, int ir, int jt, int jb, int ns, int k, float dx,
	float dz, float dt, float *vl, float *vb, float *vr,
	float *ttl, float *ttb, float *ttr)
{
	int i,j;
	float sa, ca, ak, p;
	float tw=0, tu=0, tiw, tiu, tt;
	int ksw, ksu;
	double pi=D_PI;

	/* sang = direction of wave propagation relative to vertical */
	tt=k*dt;

	/* introduce plane wave on left boundary */
	p=sin(sang*pi/180.)/vl[jb];
	for (j=jb+2; j>=jt; --j) {
		sa=sin(asin(p*vl[j]));
		ca=cos(asin(p*vl[j]));

		for (i=il-2; i<il; ++i) {
			if(sang>=0&&sang<90) { 
				tw=tt-ttl[j]-(dx*(i-il+0.75)*sa 
					+ dz*(-0.25)*ca)/vl[j];
				tu=tt-ttl[j]-(dx*(i-il+1.25)*sa 
					+ dz*(-0.75)*ca)/vl[j];
	   		}
	   		if(sang>-90&&sang<0) { 
					tw=tt-ttl[j]-(dx*(i-ir-1.75)*sa 
					+ dz*(-0.25)*ca)/vl[j];
					tu=tt-ttl[j]-(dx*(i-ir-1.25)*sa 
					+ dz*(-0.75)*ca)/vl[j];
	   		}
	   		ksw=floor(tw/dt);
			tiw=fmod(tw,dt)/dt;
	   		ksu=floor(tu/dt);
			tiu=fmod(tu,dt)/dt;
				if (ksw>=0 && ksw <ns-1) {
					ak=(1-tiw)*a[ksw]+tiw*a[ksw+1];
				w[j][i]=-vl[j]*ak*ca;
			} 

			if (ksu>=0 && ksu <ns-1) {
				ak=(1-tiu)*a[ksu]+tiu*a[ksu+1];
				u[j][i]=vl[j]*ak*sa;
			}
		}
	}

	/* introduce plane wave on right boundary */
	p=sin(sang*pi/180.)/vr[jb];
	for (j=jb+2; j>=jt; --j) {
		sa=sin(asin(p*vr[j]));
		ca=cos(asin(p*vr[j]));

		for (i=ir+1; i<ir+3; ++i) {
			if(sang>=0&&sang<90) { 
				tw=tt-ttr[j]-(dx*(i-il+1.75)*sa 
					+ dz*(-0.25)*ca)/vr[j];
				tu=tt-ttr[j]-(dx*(i-il+1.25)*sa 
					+ dz*(-0.75)*ca)/vr[j];
			}
			if(sang>-90&&sang<0) { 
				tw=tt-ttr[j]-(dx*(i-ir-0.75)*sa 
					+ dz*(-0.25)*ca)/vr[j];
				tu=tt-ttr[j]-(dx*(i-ir-1.25)*sa 
					+ dz*(-0.75)*ca)/vr[j];
		   	}
			ksw=floor(tw/dt);
			tiw=fmod(tw,dt)/dt;
			ksu=floor(tu/dt);
			tiu=fmod(tu,dt)/dt;

			if (ksw>=0 && ksw <ns-1) {
				ak=(1-tiw)*a[ksw]+tiw*a[ksw+1];
				w[j][i+1]=-vr[j]*ak*ca;
			}

			if (ksu>=0 && ksu <ns-1) {
				ak=(1-tiu)*a[ksu]+tiu*a[ksu+1];
				u[j][i]=vr[j]*ak*sa;
			}
		}
	}
	 
	/* introduce plane wave on bottom boundary */
	 if(sang>=0&&sang<90) p=sin(sang*pi/180.)/vb[il];
	 if(sang>-90&&sang<0) p=sin(sang*pi/180.)/vb[ir];
	 for (i=il; i<ir+2; ++i){
		sa=sin(asin(p*vb[i]));
		ca=cos(asin(p*vb[i]));

	  	for (j=jb-1; j<jb+3; ++j) {
			if(sang>=0&&sang<90) { 
					tw=tt-ttb[i]-(dx*(+0.75)*sa 
					+ dz*(jb-j-0.25)*ca)/vb[i];
					tu=tt-ttb[i]-(dx*(+1.25)*sa 
					+ dz*(jb-j-0.75)*ca)/vb[i];
	   		}
	   		if(sang>-90&&sang<0) { 
					tw=tt-ttb[i]-(dx*(-1.75)*sa 
					+ dz*(jb-j-0.25)*ca)/vb[i];
					tu=tt-ttb[i]-(dx*(-1.25)*sa 
					+ dz*(jb-j-0.75)*ca)/vb[i];
	   		}
	   		ksw=floor(tw/dt);
			tiw=fmod(tw,dt)/dt;
			ksu=floor(tu/dt);
			tiu=fmod(tu,dt)/dt;

			if (ksw>=0 && ksw <ns-1) {
					ak=(1-tiw)*a[ksw]+tiw*a[ksw+1];
				w[j][i]=-vb[i]*ak*ca;
	   		}
			if (ksu>=0 && ksu <ns-1) {
				ak=(1-tiu)*a[ksu]+tiu*a[ksu+1];
				u[j][i]=vb[i]*ak*sa;
	   		}
		}	
	}

}

static void add_pw_source_S(float **u, float **w, float **txx, float **tzz,
	float **txz, float **c11, float **c55, float *a, float sang,
	int il, int ir, int jt, int jb, int ns, int k, float dx,
	float dz, float dt, float *vl, float *vb, float *vr,
	float *ttl, float *ttb, float *ttr)
{
	int i,j;
	float sa, ca, ak, p;
	float tw=0, tu=0, tiw, tiu, tt;
	int ksw, ksu;
	double pi=D_PI;

	/* sang = direction of wave propagation relative to vertical */
	tt=k*dt;

	/* introduce plane wave on left boundary */
	p=sin(sang*pi/180.)/vl[jb];
	for (j=jb+2; j>=jt; --j) {
		sa=sin(asin(p*vl[j]));
		ca=cos(asin(p*vl[j]));

		for (i=il-2; i<il; ++i) {
			if(sang>=0&&sang<90) { 
				tw=tt-ttl[j]-(dx*(i-il+0.75)*sa 
					+ dz*(-0.75)*ca)/vl[j];
				tu=tt-ttl[j]-(dx*(i-il+1.25)*sa 
					+ dz*(-0.25)*ca)/vl[j];
	   		}
			if(sang>-90&&sang<0) { 
				tw=tt-ttl[j]-(dx*(i-ir-1.75)*sa 
					+ dz*(-0.75)*ca)/vl[j];
				tu=tt-ttl[j]-(dx*(i-ir-1.25)*sa 
					+ dz*(-0.25)*ca)/vl[j];
	   		}
	   		ksw=floor(tw/dt);
			tiw=fmod(tw,dt)/dt;
			ksu=floor(tu/dt);
			tiu=fmod(tu,dt)/dt;

			if (ksw>=0 && ksw <ns-1) {
				ak=(1-tiw)*a[ksw]+tiw*a[ksw+1];
				txx[j][i]=(c11[j][i]*sa*sa 
					   +(c11[j][i]-2*c55[j][i])*ca*ca)*ak;
				tzz[j][i]=(c11[j][i]*ca*ca
					   +(c11[j][i]-2*c55[j][i])*sa*sa)*ak;
	   		}
			if (ksu>=0 && ksu <ns-1) {
				ak=(1-tiu)*a[ksu]+tiu*a[ksu+1];
				txz[j][i]=c55[j][i]*(2*ca*sa)*ak;
	   		}
		}	
	}

	/* introduce plane wave on right boundary */
	 p=sin(sang*pi/180.)/vr[jb];

	for (j=jb+2; j>=jt; --j) {
		sa=sin(asin(p*vr[j]));
		ca=cos(asin(p*vr[j]));
		for (i=ir+1; i<ir+3; ++i) {
			if(sang>=0&&sang<90) { 
				tw=tt-ttr[j]-(dx*(i-il+1.75)*sa 
					+ dz*(-0.75)*ca)/vr[j];
				tu=tt-ttr[j]-(dx*(i-il+1.25)*sa 
					+ dz*(-0.25)*ca)/vr[j];
	   		}
			if(sang>-90&&sang<0) { 
				tw=tt-ttr[j]-(dx*(i-ir-0.75)*sa 
					+ dz*(-0.75)*ca)/vr[j];
				tu=tt-ttr[j]-(dx*(i-ir-1.25)*sa 
					+ dz*(-0.25)*ca)/vr[j];
	   		}
			ksw=floor(tw/dt);
			tiw=fmod(tw,dt)/dt;

			ksu=floor(tu/dt);
			tiu=fmod(tu,dt)/dt;

			if (ksw>=0 && ksw <ns-1) {
				ak=(1-tiw)*a[ksw]+tiw*a[ksw+1];
					txx[j][i+1]=(c11[j][i]*sa*sa
							+(c11[j][i]
							-2*c55[j][i])*ca*ca)*ak;
					tzz[j][i+1]=(c11[j][i]*ca*ca
							+(c11[j][i]
							-2*c55[j][i])*sa*sa)*ak;
			} else  {
				txx[j][i+1]=0;
				tzz[j][i+1]=0;
			}

			if (ksu>=0 && ksu <ns-1) {
				ak=(1-tiu)*a[ksu]+tiu*a[ksu+1];
				txz[j][i]=c55[j][i]*(2*ca*sa)*ak;
			} else {
				txz[j][i]=0;
			}
		}
	}
	 
	/* introduce plane wave on bottom boundary */
	p=sin(sang*pi/180.)/vb[il];
	for (i=il; i<ir+2; ++i){
		sa=sin(asin(p*vb[i])); ca=cos(asin(p*vb[i]));
		for (j=jb-1; j<jb+3; ++j) {
			if(sang>=0&&sang<90) { 
				tw=tt-ttb[i]-(dx*(+0.75)*sa 
					+ dz*(jb-j-0.75)*ca)/vb[i];
				tu=tt-ttb[i]-(dx*(+1.25)*sa 
					+ dz*(jb-j-0.25)*ca)/vb[i];
			}
			if(sang>-90&&sang<0) { 
				tw=tt-ttb[i]-(dx*(-1.75)*sa 
					+ dz*(jb-j-0.75)*ca)/vb[i];
				tu=tt-ttb[i]-(dx*(-1.25)*sa 
					+ dz*(jb-j-0.25)*ca)/vb[i];
	   		}
			ksw=floor(tw/dt);
			tiw=fmod(tw,dt)/dt;
			ksu=floor(tu/dt);
			tiu=fmod(tu,dt)/dt;
			if (ksw>=0 && ksw <ns-1) {
				ak=(1-tiw)*a[ksw]+tiw*a[ksw+1];
				txx[j][i]=(c11[j][i]*sa*sa
						+(c11[j][i]
							-2*c55[j][i])*ca*ca)*ak;
				tzz[j][i]=(c11[j][i]*ca*ca
						+(c11[j][i]
							-2*c55[j][i])*sa*sa)*ak;
	   		}

			if (ksu>=0 && ksu <ns-1) {
				ak=(1-tiu)*a[ksu]+tiu*a[ksu+1];
				txz[j][i]=c55[j][i]*(2*ca*sa)*ak;
	   		}
		}	
	}

}

/* absorbing bc for top*/	
static void abs_bc_top(float **u, float **w, float **txx, float **tzz,
			float **txz, int nxpadded, int nzpadded, float *r,
			int *bc, int *wbc, int ifx, int ilx)
{
	int i,j; float fac;
		
	for (j=0; j<wbc[0]; ++j){
		fac=r[(wbc[0]-j-1)];
		for (i=ifx; i<ilx; ++i){
				u[j][i]*=fac;
			w[j][i]*=fac;
				txx[j][i]*=fac;
			tzz[j][i]*=fac;
			txz[j][i]*=fac;
		}
	}
}

/* absorbing bc for left side*/	
static void abs_bc_left(float **u, float **w, float **txx, float **tzz,
			float **txz, int nxpadded, int nzpadded, float *r,
			int *bc, int *wbc, int jfz, int jlz)
{
	int i,j;
	float fac;
		
	for (j=jfz; j<jlz; ++j){
		for (i=0; i<wbc[1]; ++i){
			fac=r[(wbc[1]-i-1)];
				u[j][i]*=fac;
			w[j][i]*=fac;
				txx[j][i]*=fac;
			tzz[j][i]*=fac;
			txz[j][i]*=fac;
		}
	}
}

/* absorbing bc for bottom*/	
static void abs_bc_bot(float **u, float **w, float **txx, float **tzz,
			float **txz, int nxpadded, int nzpadded, float *r,
			int *bc, int *wbc, int ifx, int ilx)
{
	int i,j;
	float fac;
		
	for (j=nzpadded-wbc[2]; j<nzpadded; ++j){
		fac=r[(j-nzpadded+wbc[2])];
	  	for (i=ifx; i<ilx; ++i){
				u[j][i]*=fac;
			w[j][i]*=fac;
				txx[j][i]*=fac;
			tzz[j][i]*=fac;
			txz[j][i]*=fac;
		}
	}		
}

/* absorbing bc for right side*/	
static void abs_bc_right(float **u, float **w, float **txx, float **tzz,
			float **txz, int nxpadded, int nzpadded, float *r, 
			int *bc, int *wbc, int jfz, int jlz)
{
	int i,j;
	float fac;
		
	for (j=jfz; j<jlz; ++j){
		for (i=nxpadded-wbc[3]; i<nxpadded; ++i){
				fac=r[(i-nxpadded+wbc[3])];
				u[j][i]*=fac;
			w[j][i+1]*=fac;
				txx[j][i+1]*=fac;
			tzz[j][i+1]*=fac;
			txz[j][i]*=fac;
		}
	}
}
	
/* Free surface boundary condition where stresses are set to zero
   for the order 4 FD operater on a staggered grid */
static void fs4s_bc_top(float **txx, float **tzz, float **txz, int nxpadded, int nzpadded)
{
	int i;
		
	for (i=2; i<nxpadded-2; ++i){
	 		txz[1][i]=0.; txz[0][i]=0.; txz[2][i]=0.;
	}
	for (i=2; i<nxpadded-1; ++i){
	 		txx[1][i]=0.; txx[0][i]=0.; 
	 		tzz[1][i]=-tzz[2][i]; tzz[0][i]=-tzz[3][i];
	}
}

/* Free surface boundary condition where velocities satisfy stress free
  surface for the order 4 FD operater on a staggered grid

** requires anisotropy symmetry parallel to free surface in 
** current implementation */

static void fs4v_bc_top(float **u, float **w, float **c11,
			float **c55, int nxpadded, int nzpadded)
{
	int i;
	
	/*  	010514-split loop into two four parts as it was 
		in original FORTRAN CODE, previous versions 
		were calculating all vaulues at once	 */

	for (i=2; i<nxpadded-2; ++i){
		u[0][i]=u[2][i]
			+ 2*( F1*(w[2][i+1]-w[2][i]) 
			+ F2*(w[2][i+2]-w[2][i-1]) );
	}

	for (i=2; i<nxpadded-1; ++i){
		w[0][i]=w[2][i]
			+ 2*(1-2*(c55[2][i]/c11[2][i]))
			*( F1*(u[0][i]-u[0][i-1]) 
			+ F2*(u[0][i+1]-u[0][i-2]) );
	}
	for (i=2; i<nxpadded-2; ++i){
		u[1][i]=u[0][i]
			+ 2*( F1*(w[2][i+1]-w[2][i])
				+ F2*(w[2][i+2]-w[2][i-1]) );
	}
	for (i=2; i<nxpadded-1; ++i){
		w[1][i]=w[0][i]
			+ 2*(1-2*(c55[2][i]/c11[2][i]))
			*( F1*(u[1][i]-u[1][i-1]) 
				+ F2*(u[1][i+1]-u[1][i-2]) );
	}
}

static void sym4s_bc_top(float **txx, float **tzz, float **txz, int nxpadded, int nzpadded)
/* Stress symmetry boundary condition for the TOP boundary
   for the order 4 FD operater on a staggered grid */
{
	int i;
		
	for (i=2; i<nxpadded-2; ++i){
	 		txx[1][i]=txx[2][i];  txx[0][i]=txx[3][i]; 
	 		tzz[1][i]=tzz[2][i];  tzz[0][i]=tzz[3][i];
	 		txz[1][i]=-txz[3][i]; txz[0][i]=-txz[4][i];
	}
}

static void sym4v_bc_top(float **u, float **w, int nxpadded, int nzpadded)
/* Velocity symmetry boundary condition for the TOP boundary
   for the order 4 FD operater on a staggered grid */
{
	int i;
		
	for (i=2; i<nxpadded-2; ++i){
	 		u[1][i]=u[2][i];  u[0][i]=u[3][i]; 
	 		w[1][i]=-w[3][i]; w[0][i]=-w[4][i];
	}
}

static void sym4s_bc_right(float **txx, float **tzz, float **txz, int nxpadded, int nzpadded)
/* Stress symmetry boundary condition for the RHS boundary
   for the order 4 FD operater on a staggered grid */
{
	int j;
		
	for (j=0; j<nzpadded; ++j){
	 		txx[j][nxpadded]=txx[j][nxpadded-4]; txx[j][nxpadded-1]=txx[j][nxpadded-3]; 
	 		tzz[j][nxpadded]=tzz[j][nxpadded-4]; tzz[j][nxpadded-1]=tzz[j][nxpadded-3];
	 		txz[j][nxpadded-1]=-txz[j][nxpadded-4]; txz[j][nxpadded-2]=-txz[j][nxpadded-3];
	}
}

static void sym4v_bc_right(float **u, float **w, int nxpadded, int nzpadded)
/* Velocity symmetry boundary condition for the RHS boundary
   for the order 4 FD operater on a staggered grid */
{
	int j;
		
	for (j=0; j<nzpadded; ++j){
	 		u[j][nxpadded-1]=-u[j][nxpadded-4]; u[j][nxpadded-2]=-u[j][nxpadded-3]; 
	 		w[j][nxpadded]=w[j][nxpadded-4]; w[j][nxpadded-1]=w[j][nxpadded-3];
	}
}

static void sym4s_bc_left(float **txx, float **tzz, float **txz, int nxpadded, int nzpadded)
/* Stress symmetry boundary condition for the LHS boundary
   for the order 4 FD operater on a staggered grid */
{
	int j;
		
	for (j=0; j<nzpadded; ++j){
	 		txx[j][1]=txx[j][3]; txx[j][0]=txx[j][4]; 
	 		tzz[j][1]=tzz[j][3];  tzz[j][0]=tzz[j][4];
	 		txz[j][1]=-txz[j][2]; txz[j][0]=-txz[j][3];
	}
}

static void sym4v_bc_left(float **u, float **w, int nxpadded, int nzpadded)
/* Velocity symmetry boundary condition for the LHS boundary
   for the order 4 FD operater on a staggered grid */
{
	int j;
		
	for (j=0; j<nzpadded; ++j){
	 		u[j][1]=-u[j][2]; u[j][0]=-u[j][3]; 
	 		w[j][1]=w[j][3]; w[j][0]=w[j][4];
	}
}

static void sym4s_bc_bot(float **txx, float **tzz, float **txz, int nxpadded, int nzpadded)
/* Stress symmetry boundary condition for the BOTTOM boundary
   for the order 4 FD operater on a staggered grid */
{
	int i;
		
	for (i=2; i<nxpadded-2; ++i){
/*	 		txx[nzpadded-2][i]=txx[nzpadded-4][i];  txx[nzpadded-1][i]=txx[nzpadded-5][i];  */
/*	 		tzz[nzpadded-2][i]=-tzz[nzpadded-4][i]; tzz[nzpadded-1][i]=-tzz[nzpadded-5][i]; */
/*	 		txz[nzpadded-2][i]=-txz[nzpadded-3][i]; txz[nzpadded-1][i]=-txz[nzpadded-4][i];} */
	 		txx[nzpadded-2][i]=txx[nzpadded-4][i];  txx[nzpadded-1][i]=txx[nzpadded-5][i]; 
	 		tzz[nzpadded-2][i]=tzz[nzpadded-4][i]; tzz[nzpadded-1][i]=tzz[nzpadded-5][i];
	 		txz[nzpadded-2][i]=-txz[nzpadded-3][i]; txz[nzpadded-1][i]=-txz[nzpadded-4][i];
	}
}

static void sym4v_bc_bot(float **u, float **w, int nxpadded, int nzpadded)
/* Velocity symmetry boundary condition for the BOTTOM boundary
   for the order 4 FD operater on a staggered grid */
{
	int i;
		
	for (i=2; i<nxpadded-2; ++i){
/*	 		u[nzpadded-2][i]=u[nzpadded-4][i]; u[nzpadded-1][i]=u[nzpadded-5][i];  */
/*	 		w[nzpadded-2][i]=-w[nzpadded-3][i];w[nzpadded-1][i]=-w[nzpadded-4][i];} */
	 		u[nzpadded-2][i]=u[nzpadded-4][i]; u[nzpadded-1][i]=u[nzpadded-5][i]; 
	 		w[nzpadded-2][i]=-w[nzpadded-3][i]; w[nzpadded-1][i]=-w[nzpadded-4][i];
	}
}

static void calc_area(float vmax, float dtx, float dtz, 
		int *limits, int i, int j, int k, int nxpadded, int nzpadded)
{
	 limits[0] = i - NINT(vmax*k*dtx) - 10;
	 limits[1] = i + NINT(vmax*k*dtx) + 10;
	 limits[2] = j - NINT(vmax*k*dtz) - 10;
	 limits[3] = j + NINT(vmax*k*dtz) + 10;

	 if (limits[0] < 2) limits[0] = 2;

	 if (limits[1] > nxpadded-3) limits[1] = nxpadded-3;

	 if (limits[2] < 2) limits[2] = 2;

	 if (limits[3] > nzpadded-3) limits[3] = nzpadded-3;	 
}




/* Library version of SUEA2DF
 *
 * The main program (the parameters, the files of the model, of the snapshots and of the seismograms, the character headers) is left
 * to the caller. The computation is made in steps, on a model that the caller makes, steps and frees, and all of the arrays that the
 * caller gives are not changed:
 *
 *	su_ea2df_create:	pads and checks the model, makes the source, the boundary tapers and the traveltimes of a plane wave
 *	su_ea2df_step:		the next time step (the program's loop body), recording the horizontal and vertical lines
 *	su_ea2df_snapshot:	copies a field of the model (without the boundary layers) at this time
 *	su_ea2df_info, su_ea2df_lines:	the sizes, and the recorded lines (after the model has been stepped nt times)
 *	su_ea2df_free:		frees the model
 *
 * The 2-D arrays that are given are [nz][nx] (x the fast axis), as the program reads them: the stiffnesses c11 and c55, and (with
 * aniso) c13, c33, c15 and c35, the density (rho) and (with qsw) the Q-factor.
 *
 * Differences from the program:
 *  - The padding of the model (pad_float_2D) is done correctly: the model is copied into the padded array, shifted by the widths of
 *    the boundary layers, and the edges are extended into the layers. The program's copy loops stopped at the end of the unpadded
 *    model (so that the last rows and columns of the model were lost, and the model was shifted in the padded array), with the
 *    layers beyond it filled from the last row and column.
 *  - The loop does nt = NINT((lt-ft)/dt)+1 steps. The program counted the time in single precision (t=t+dt while t<=lt), which could
 *    be one step more or less than the nt of the arrays that record it.
 *  - The checks of the parameters return a code.
 */

struct Ea2dfModel {
	int nx, nz, nxpadded, nzpadded, nt, k, ns, aniso, qsw, tsw, stype, bc[4], wbc[4], is, js, hs1, vs2, limits[4];
	float dt, dx, dz, fx, fz, sang, vlim[2], dtx, dtz;
	float **c11, **c55, **c13, **c33, **c15, **c35, **rho, **q;
	float **u, **w, **txx, **tzz, **txz;
	float *source, *bc0, *bc1, *bc2, *bc3, *vl, *vr, *vb, *ttl, *ttr, *ttb;
	float **hu, **hw, **vu, **vw;	/* the lines recorded: [nt][nxpadded], [nt][nzpadded] */
};

/* the padding of an [n2][n1] array to [n2+padval[0]+padval[2]][n1+padval[1]+padval[3]]: copied, with the edges extended */
static void pad_model(int n1, int n2, int *padval, const float *in, float **out)
{
	int ix1, ix2, j1, j2, n1padded = n1+padval[1]+padval[3], n2padded = n2+padval[0]+padval[2];
	for (ix2=0; ix2<n2padded; ++ix2) {
		j2 = ix2-padval[0];
		if (j2<0) j2 = 0;
		if (j2>n2-1) j2 = n2-1;
		for (ix1=0; ix1<n1padded; ++ix1) {
			j1 = ix1-padval[1];
			if (j1<0) j1 = 0;
			if (j1>n1-1) j1 = n1-1;
			out[ix2][ix1] = in[(size_t)j2*n1+j1];
		}
	}
}

static void ea_minmax(float **a, int nxpadded, int nzpadded, float *amin, float *amax)
{
	int ix, iz;
	*amin = *amax = a[0][0];
	for (iz=0; iz<nzpadded; ++iz)
		for (ix=0; ix<nxpadded; ++ix) {
			if (a[iz][ix]<*amin) *amin = a[iz][ix];
			if (a[iz][ix]>*amax) *amax = a[iz][ix];
		}
}

/* Returns the model, or NULL and in *err: -1 or -2 the source is outside of the model in x or z, -3 parameters that are not allowed,
 * -4 an unknown source or wave type, -5 a recording line outside of the model, -6 a density or Q that is not positive. */
struct Ea2dfModel *su_ea2df_create(float dt, float ft, float lt, int nx, float dx, float fx, int nz, float dz, float fz,
	float sx, float sz, const char *stype, float sang, const char *wtype, float ts, float favg,
	int qsw, int aniso, int tsw, const int *bcin, float bc_a, float bc_r, float hsz, float vsx,
	const float *c11in, const float *c55in, const float *rhoin, const float *c13in, const float *c33in,
	const float *c15in, const float *c35in, const float *qin, int *err)
{
	struct Ea2dfModel *M;
	int i, j, ix, iz, nxpadded, nzpadded, nt, ns, ngrids = 0;
	int bc[4], wbc[4];
	float xmax, zmax, rhomin, rhomax, c11min, c11max, c55min, c55max, dummy, sa, ca, p;
	float **c11, **c55, **rho, **c13 = NULL, **c33 = NULL, **c15 = NULL, **c35 = NULL, **q = NULL;
	float *bc0, *bc1, *bc2, *bc3, *source, *vl, *vr, *vb, *ttl, *ttr, *ttb;
	float vlim[2];
	int stype_code;

	*err = 0;
	if (dt<=0.0 || dx<=0.0 || dz<=0.0 || nx<5 || nz<5 || lt<ft || ts<0.0 || favg<=0.0) { *err = -3; return NULL; }
	if (strcmp(stype,"p")==0) stype_code = 0;
	else if (strcmp(stype,"v")==0) stype_code = 1;
	else if (strcmp(stype,"pw")==0) stype_code = 2;
	else { *err = -4; return NULL; }
	if (strcmp(wtype,"ri")!=0 && strcmp(wtype,"dg")!=0 && strcmp(wtype,"ga")!=0 && strcmp(wtype,"sp")!=0 && strcmp(wtype,"sp2")!=0) {
		*err = -4; return NULL;
	}
	for (i=0; i<4; i++) { bc[i] = bcin[i]; if (bc[i]<0) { *err = -3; return NULL; } }

	/* calculate maximum model coordinates */
	xmax = fx + dx*nx;
	zmax = fz + dz*nz;

	/* check to see if source is inside the model */
	if ((sx<fx) || (sx>xmax)) { *err = -1; return NULL; }
	if ((sz<fz) || (sz>zmax)) { *err = -2; return NULL; }

	for (i=0; i<4; i++) {
		wbc[i] = 2;
		if (bc[i]>2) wbc[i] = bc[i];
	}
	bc0 = ealloc1float(bc[0]+1);
	bc1 = ealloc1float(bc[1]+1);
	bc2 = ealloc1float(bc[2]+1);
	bc3 = ealloc1float(bc[3]+1);
	bc0[0] = bc_a;
	bc1[0] = bc_a;
	bc2[0] = bc_a;
	bc3[0] = bc_a;
	for (j=1; j<bc[0]; j++) bc0[j] = bc0[j-1]*bc_a*pow(j,-bc_r);
	for (j=1; j<bc[1]; j++) bc1[j] = bc1[j-1]*bc_a*pow(j,-bc_r);
	for (j=1; j<bc[2]; j++) bc2[j] = bc2[j-1]*bc_a*pow(j,-bc_r);
	for (j=1; j<bc[3]; j++) bc3[j] = bc3[j-1]*bc_a*pow(j,-bc_r);

	/* the recording lines */
	M = (struct Ea2dfModel*)calloc(1,sizeof(struct Ea2dfModel));
	M->hs1 = NINT( (hsz - fz)/dz )+wbc[0];		/*horizontal line*/
	M->vs2 = NINT((vsx - fx)/dx )+wbc[1];		/*vertical line*/

	/* pad the nx and nz dimensions for boundary condition layers */
	nxpadded = nx+wbc[1]+wbc[3];
	nzpadded = nz+wbc[0]+wbc[2];
	if (M->hs1<0 || M->hs1>=nzpadded || M->vs2<0 || M->vs2>=nxpadded) {
		*err = -5; free(M); free1float(bc0); free1float(bc1); free1float(bc2); free1float(bc3); return NULL;
	}
	nt = NINT((lt-ft)/dt)+1;

	M->dtx = dt/dx; M->dtz = dt/dz;
	M->is = NINT((-fx+sx)/dx)+wbc[1]; M->js = NINT((-fz+sz)/dz)+wbc[0];

	/* the model, padded */
	c11 = ealloc2float(nxpadded,nzpadded);
	c55 = ealloc2float(nxpadded,nzpadded);
	rho = ealloc2float(nxpadded,nzpadded);
	pad_model(nx,nz,wbc,c11in,c11);
	pad_model(nx,nz,wbc,c55in,c55);
	pad_model(nx,nz,wbc,rhoin,rho);
	ngrids = 3;
	if (aniso==1) {
		c33 = ealloc2float(nxpadded,nzpadded);
		c13 = ealloc2float(nxpadded,nzpadded);
		c15 = ealloc2float(nxpadded,nzpadded);
		c35 = ealloc2float(nxpadded,nzpadded);
		pad_model(nx,nz,wbc,c33in,c33);
		pad_model(nx,nz,wbc,c13in,c13);
		pad_model(nx,nz,wbc,c15in,c15);
		pad_model(nx,nz,wbc,c35in,c35);
	}
	if (qsw==1) {
		q = ealloc2float(nxpadded,nzpadded);
		pad_model(nx,nz,wbc,qin,q);
	}

	/* we need to invert density */
	ea_minmax(rho,nxpadded,nzpadded,&rhomin,&rhomax);
	if (rhomin<=0.0) {
		*err = -6;
		free2float(c11); free2float(c55); free2float(rho);
		if (aniso==1) { free2float(c33); free2float(c13); free2float(c15); free2float(c35); }
		if (qsw==1) free2float(q);
		free(M); free1float(bc0); free1float(bc1); free1float(bc2); free1float(bc3);
		return NULL;
	}
	rhomin = rhomax = 1/rho[0][0];
	for (iz=0; iz<nzpadded; ++iz) {
		for (ix=0; ix<nxpadded; ++ix) {
			/* rho = 1/rho */
			rho[iz][ix] = 1/rho[iz][ix];
			rhomin = MIN(rhomin,rho[iz][ix]);
			rhomax = MAX(rhomax,rho[iz][ix]);
		}
	}
	ea_minmax(c11,nxpadded,nzpadded,&c11min,&c11max);
	ea_minmax(c55,nxpadded,nzpadded,&c55min,&c55max);
	(void)c55min; (void)c55max; (void)dummy; (void)ngrids;

	vlim[0] = sqrt(c11min*rhomax);
	vlim[1] = sqrt(c11max*rhomin);

	if (qsw==1) {
		ea_minmax(q,nxpadded,nzpadded,&dummy,&dummy);
		/* scale Q-factor */
		for (i=0; i<nxpadded; i++){
			for (j=0; j<nzpadded; j++) {
				q[j][i] = exp(-PI*dt*favg/q[j][i]);
			}
		}
	}

	/* set arrays for plane boundary conditions */
	ttl = ealloc1float(nzpadded);
	ttb = ealloc1float(nxpadded);
	ttr = ealloc1float(nzpadded);
	vl = ealloc1float(nzpadded);
	vb = ealloc1float(nxpadded);
	vr = ealloc1float(nzpadded);

	/* note that rho = 1/density now */
	for (j=0; j<nzpadded; ++j) {
		vl[j]=sqrt(c11[j][wbc[1]]*rho[j][wbc[1]]);
		vr[j]=sqrt(c11[j][nxpadded-wbc[3]-1]*rho[j][nxpadded-wbc[3]-1]);
	}
	for (i=0; i<nxpadded; ++i) {
		vb[i]=sqrt(c11[nzpadded-wbc[2]-1][i]*rho[nzpadded-wbc[2]-1][i]);
	}
	for (i=0; i<nxpadded; ++i) ttb[i] = 0.0;

	/* ttb: traveltime from source to location on bottom */
	sa=sin(PI*sang/180.);ca=cos(PI*sang/180.);

	if(sang>=0&&sang<90){
		ttb[0]=(-wbc[1])*sa*dx/vb[wbc[1]];
		for (i=1; i<nxpadded; ++i) {
			ttb[i]=ttb[i-1]+dx*sa/vb[i];
		}
	}

	if(sang>-90&&sang<0){
		ttb[nxpadded-1]=-(-wbc[3])*sa*dx/vl[nxpadded-wbc[3]-1];
		for (i=nxpadded-1; i>0; --i) {
			ttb[i-1]=ttb[i]-dx*sa/vb[i];
		}
	}

	/* ttl, ttr: traveltimes from source to location on LHS, RHS */
	sa=sin(PI*sang/180.);
	ca=cos(PI*sang/180.);
	p=sin(sang*PI/180.)/vl[nzpadded-wbc[2]-1];

	ttl[nzpadded-1]=(-wbc[2])*ca*dz/vl[nzpadded-wbc[2]-1];
	for (j=nzpadded-1; j>0; --j) {
		sa=sin(asin(p*vl[j]));
		ca=cos(asin(p*vl[j]));
		ttl[j-1]=ttl[j]+dz*ca/vl[j];
	}

	sa=sin(PI*sang/180.);
	ca=cos(PI*sang/180.);
	p=sin(sang*PI/180.)/vr[nzpadded-wbc[2]-1];
	ttr[nzpadded-1]=(-wbc[2])*ca*dz/vr[nzpadded-wbc[2]-1];

	for (j=nzpadded-1; j>0; --j) {
		sa=sin(asin(p*vr[j]));
		ca=cos(asin(p*vr[j]));
		ttr[j-1]=ttr[j]+dz*ca/vr[j];
	}

	/* get source function */
	ns = NINT(ts/dt)+1;
	source = ealloc1float(ns);
	get_source(dt,ts,favg,(char*)wtype,source);

	/* allocate space for variables */
	M->u = ealloc2float(nxpadded,nzpadded);
	M->w = ealloc2float(nxpadded+1,nzpadded);
	M->txx = ealloc2float(nxpadded+1,nzpadded);
	M->tzz = ealloc2float(nxpadded+1,nzpadded);
	M->txz = ealloc2float(nxpadded,nzpadded);
	memset(M->u[0],0,sizeof(float)*(size_t)nxpadded*nzpadded);
	memset(M->w[0],0,sizeof(float)*(size_t)(nxpadded+1)*nzpadded);
	memset(M->txx[0],0,sizeof(float)*(size_t)(nxpadded+1)*nzpadded);
	memset(M->tzz[0],0,sizeof(float)*(size_t)(nxpadded+1)*nzpadded);
	memset(M->txz[0],0,sizeof(float)*(size_t)nxpadded*nzpadded);

	M->hu = ealloc2float(nxpadded,nt);
	M->hw = ealloc2float(nxpadded,nt);
	M->vu = ealloc2float(nzpadded,nt);
	M->vw = ealloc2float(nzpadded,nt);

	M->nx = nx; M->nz = nz; M->nxpadded = nxpadded; M->nzpadded = nzpadded; M->nt = nt; M->k = 0; M->ns = ns;
	M->aniso = aniso; M->qsw = qsw; M->tsw = tsw; M->stype = stype_code;
	for (i=0; i<4; i++) { M->bc[i] = bc[i]; M->wbc[i] = wbc[i]; }
	M->dt = dt; M->dx = dx; M->dz = dz; M->fx = fx; M->fz = fz; M->sang = sang;
	M->vlim[0] = vlim[0]; M->vlim[1] = vlim[1];
	M->c11 = c11; M->c55 = c55; M->c13 = c13; M->c33 = c33; M->c15 = c15; M->c35 = c35; M->rho = rho; M->q = q;
	M->source = source; M->bc0 = bc0; M->bc1 = bc1; M->bc2 = bc2; M->bc3 = bc3;
	M->vl = vl; M->vr = vr; M->vb = vb; M->ttl = ttl; M->ttr = ttr; M->ttb = ttb;
	return M;
}

/* The sizes: the padded model, the number of time steps, the widths of the boundary layers wbc[4], and the number of steps done */
void su_ea2df_info(const struct Ea2dfModel *M, int *nxpadded, int *nzpadded, int *nt, int *wbc, int *done)
{
	int i;
	*nxpadded = M->nxpadded; *nzpadded = M->nzpadded; *nt = M->nt; *done = M->k;
	for (i=0; i<4; i++) wbc[i] = M->wbc[i];
}

/* The lines recorded, each [nt][n]: hu, hw (the horizontal line, n=nxpadded), vu, vw (the vertical line, n=nzpadded) */
void su_ea2df_lines(const struct Ea2dfModel *M, const float **hu, const float **hw, const float **vu, const float **vw)
{
	*hu = M->hu[0]; *hw = M->hw[0]; *vu = M->vu[0]; *vw = M->vw[0];
}

/* Copies a field without the boundary layers, [nz][nx], to out: which is 0 u, 1 w, 2 txx, 3 tzz, 4 txz */
void su_ea2df_snapshot(const struct Ea2dfModel *M, int which, float *out)
{
	float **f = (which==0) ? M->u : (which==1) ? M->w : (which==2) ? M->txx : (which==3) ? M->tzz : M->txz;
	int i, j;
	for (j=0; j<M->nz; ++j)
		for (i=0; i<M->nx; ++i)
			out[(size_t)j*M->nx+i] = f[j+M->wbc[0]][i+M->wbc[1]];
}

/* The next time step. Returns 1 if the model was stepped, 0 if it has done nt steps. */
int su_ea2df_step(struct Ea2dfModel *M)
{
	int ifx, ilx, jfz, jlz, i, j, k = M->k;
	int nxpadded = M->nxpadded, nzpadded = M->nzpadded, ns = M->ns;
	int *wbc = M->wbc, *bc = M->bc, *limits = M->limits;
	float **u = M->u, **w = M->w, **txx = M->txx, **tzz = M->tzz, **txz = M->txz;
	float **c11 = M->c11, **c55 = M->c55, **c33 = M->c33, **c13 = M->c13, **c15 = M->c15, **c35 = M->c35, **rho = M->rho, **q = M->q;
	float dtx = M->dtx, dtz = M->dtz, dt = M->dt, dx = M->dx, dz = M->dz, sang = M->sang;
	float *source = M->source;
	int is = M->is, js = M->js, aniso = M->aniso, qsw = M->qsw, tsw = M->tsw, stype = M->stype;

	if (k>=M->nt) return 0;

	/* calculate area for active grid */
	calc_area(M->vlim[1],dtx,dtz,limits,is,js,k,nxpadded,nzpadded);

	ifx=limits[0];
	ilx=limits[1];
	jfz=limits[2];
	jlz=limits[3];

	if (stype==2){
		ifx=2;
		ilx=nxpadded-3;
		jfz=2;
		jlz=nzpadded-3;
	}

	/* introduce velocity source */
	if (k<ns) {
		if (stype==1)
			add_v_source(u,w,dt*source[k],is,js);
	}

	/* update velocities */
	if(tsw==0)
		update_vel(ifx,ilx,jfz,jlz,u,w,txx,tzz,txz,
				rho,c55,dtx,dtz);
	if(tsw==1)
		update_vel_tsw(ifx,ilx,jfz,jlz,u,w,txx,tzz,
				txz,rho,c55,dtx,dtz);

	/* introduce plane wave velocity source */
	if (stype==2){
		add_pw_source_V(u,w,txx,tzz,txz,c11,c55,
				source,sang,wbc[1],
				nxpadded-wbc[3]-1,
				wbc[0],nzpadded-wbc[2]-1,
				ns,k,dx,dz,dt,M->vl,M->vb,M->vr,
				M->ttl,M->ttb,M->ttr);
	}

	/* apply free surface bc for velocities */
	if(bc[0]==2) fs4v_bc_top(u,w,c11,c55,nxpadded,nzpadded);

	/* apply symmetry bc for velocities */
	if(bc[0]==1) sym4v_bc_top(u,w,nxpadded,nzpadded);
	if(bc[1]==1) sym4v_bc_left(u,w,nxpadded,nzpadded);
	if(bc[2]==1) sym4v_bc_bot(u,w,nxpadded,nzpadded);
	if(bc[3]==1) sym4v_bc_right(u,w,nxpadded,nzpadded);

	/* introduce stress source */
	if (k<ns) {
		if (stype==0)
			add_p_source(txx,tzz,dt*source[k],is,js);
	}

	/* update stresses */
	if(!aniso) {  /* isotropic */
		update_stress_iso(ifx,ilx,jfz,jlz,u,w,txx,tzz,txz,
				c11,c55,dtx,dtz);
	} else {
		update_stress_ani(ifx,ilx,jfz,jlz,u,w,txx,tzz,txz,
				c11,c55,c33,c13,c15,c35,
				dtx,dtz);
	}

	/* introduce plane wave stress source */
	if (stype==2) {
		add_pw_source_S(u,w,txx,tzz,txz,c11,c55,
				source,sang,wbc[1],
				nxpadded-wbc[3]-1,wbc[0],
				nzpadded-wbc[2]-1,ns,k,
				dx,dz,dt,M->vl,M->vb,M->vr,M->ttl,
				M->ttb,M->ttr);
	}

	/* apply free surface bc for stresses */
	if(bc[0]==2) fs4s_bc_top(txx,tzz,txz,nxpadded,nzpadded);

	/* apply symmetry bc for stresses */
	if(bc[0]==1) sym4s_bc_top(txx,tzz,txz,nxpadded,nzpadded);
	if(bc[1]==1) sym4s_bc_left(txx,tzz,txz,nxpadded,nzpadded);
	if(bc[2]==1) sym4s_bc_bot(txx,tzz,txz,nxpadded,nzpadded);
	if(bc[3]==1) sym4s_bc_right(txx,tzz,txz,nxpadded,nzpadded);

	/* apply absorbing bc */
	if(bc[0]>2)
		abs_bc_top(u,w,txx,tzz,txz,nxpadded,nzpadded,
				M->bc0,bc,wbc,ifx,ilx);
	if(bc[1]>2)
		abs_bc_left(u,w,txx,tzz,txz,nxpadded,nzpadded,
				M->bc1,bc,wbc,jfz,jlz);
	if(bc[2]>2)
		abs_bc_bot(u,w,txx,tzz,txz,nxpadded,nzpadded,
				M->bc2,bc,wbc,ifx,ilx);
	if(bc[3]>2)
		abs_bc_right(u,w,txx,tzz,txz,nxpadded,nzpadded,
				M->bc3,bc,wbc,jfz,jlz);

	/* attenuation */
	if(qsw==1) {
		for (j=jfz-2; j<jlz+2; j++){
			for (i=ifx-2; i<ilx+2; i++) {
				u[j][i]*=q[j][i];
				w[j][i]*=q[j][i];
				txx[j][i]*=q[j][i];
				tzz[j][i]*=q[j][i];
				txz[j][i]*=q[j][i];
			}
		}
	}

	/* store wave motion (seismograms) */
	for (i=0 ; i < nxpadded ; ++i) {
		M->hu[k][i] = u[M->hs1][i];
		M->hw[k][i] = w[M->hs1][i];
	}
	for (j=0 ; j < nzpadded ; ++j) {
		M->vu[k][j] = u[j][M->vs2];
		M->vw[k][j] = w[j][M->vs2];
	}

	M->k = k+1;
	return 1;
}

void su_ea2df_free(struct Ea2dfModel *M)
{
	if (M==NULL) return;
	free2float(M->c11); free2float(M->c55); free2float(M->rho);
	if (M->aniso==1) { free2float(M->c33); free2float(M->c13); free2float(M->c15); free2float(M->c35); }
	if (M->qsw==1) free2float(M->q);
	free2float(M->u); free2float(M->w); free2float(M->txx); free2float(M->tzz); free2float(M->txz);
	free2float(M->hu); free2float(M->hw); free2float(M->vu); free2float(M->vw);
	free1float(M->source); free1float(M->bc0); free1float(M->bc1); free1float(M->bc2); free1float(M->bc3);
	free1float(M->vl); free1float(M->vr); free1float(M->vb); free1float(M->ttl); free1float(M->ttr); free1float(M->ttb);
	free(M);
}
