su_main_srcs = []

subdir('amplitudes')
subdir('filters')
subdir('operations')
subdir('stretching_moveout_resamp')
subdir('synthetics_waveforms_testpatterns')
subdir('tapering')
subdir('windowing_sorting_muting')
subdir('attributes_parameter_estimation')
subdir('transforms')
subdir('convolution_correlation')
subdir('noise')
subdir('stacking')
subdir('velocity_analysis')
subdir('migration_inversion')
