/* Copyright (c) Colorado School of Mines, 2011.*/
/* All rights reserved.                       */

/* SUKDMIG2D: $Revision: 1.26 $ ; $Date: 2011/11/16 22:14:43 $	*/

#include "su.h"
#include "segy.h"

/*********************** self documentation **********************/
#if 0 /* the sdoc of the program, which is not part of the library */
char *sdoc[] = {
" 									",
"SUKDMIG2D - Kirchhoff Depth Migration of 2D poststack/prestack data	",
" 									",
"    sukdmig2d  infile=  outfile=  ttfile=   [parameters] 		",
"									",
" Required parameters:							",
" infile=stdin		file for input seismic traces			",
" outfile=stdout	file for common offset migration output  	",
" ttfile=		file for input traveltime tables		",
"									",
" ...  The following 9 parameters describe traveltime tables:		",
" fzt= 			first depth sample in traveltime table		",
" nzt= 			number of depth samples in traveltime table	",
" dzt=			depth interval in traveltime table		",
" fxt=			first lateral sample in traveltime table	",
" nxt=			number of lateral samples in traveltime table	",
" dxt=			lateral interval in traveltime table		",
" fs= 			x-coordinate of first source			",
" ns= 			number of sources				",
" ds= 			x-coordinate increment of sources		",
"									",
" Optional Parameters:							",
" dt= or from header (dt) 	time sampling interval of input data	",
" ft= or from header (ft) 	first time sample of input data		",
" dxm= or from header (d2) 	sampling interval of midpoints 		",
" fzo=fzt		    z-coordinate of first point in output trace	",
" dzo=0.2*dzt		vertical spacing of output trace 		",
" nzo=5*(nzt-1)+1 	number of points in output trace		",	
" fxo=fxt		    x-coordinate of first output trace 		",
" dxo=0.5*dxt		horizontal spacing of output trace 		",
" nxo=2*(nxt-1)+1  	number of output traces 			",	
" off0=0		   	first offest in output 			",
" doff=99999		offset increment in output 			",
" noff=1	 	number of offsets in output 			",	
" absoff=0      flag for using absolute offsets of input traces		",
"               =0 means use offset=gx-sx                		",
"               =1 means use abs(gx-sx)                  		",
" limoff=0      flag for only using input traces that fall within the range",
"               of defined output offset bins (off0,doff,noff) 		",
"               =0 means use all input traces                 		",
"               =1 means limit traces used by offset           		",
" fmax=0.25/dt		frequency-highcut for input traces		",
" offmax=99999		maximum absolute offset allowed in migration 	",
" aperx=nxt*dxt/2  	migration lateral aperature 			",
" angmax=60		migration angle aperature from vertical 	",
" v0=1500(m/s)		reference velocity value at surface		",	
" dvz=0.0  		reference velocity vertical gradient		",
"									",
" ls=1			flag for line source				",
" jpfile=stderr		job print file name 				",
"									",
" mtr=100  		print verbal information at every mtr traces	",
" ntr=100000		maximum number of input traces to be migrated	",
" npv=0			flag of computing quantities for velocity analysis",
" rscale=1000.0 	scaling for roundoff error suppression		",
"									",
"   ...if npv>0 specify the following three files:			",
" tvfile=tvfile		input file of traveltime variation tables	",
"			tv[ns][nxt][nzt]				",
" csfile=csfile		input file of cosine tables cs[ns][nxt][nzt]	",
" outfile1=outfile1	file containning additional migration output   	",
"			with extra amplitude				",
"									",
" Notes:								",
" 1. Traveltime tables were generated by program rayt2d (or other ones)	",
"    on relatively coarse grids, with dimension ns*nxt*nzt. In the	",
"    migration process, traveltimes are interpolated into shot/gephone 	",
"    positions and output grids.					",
" 2. Input seismic traces must be SU format and can be any type of 	",
"    gathers (common shot, common offset, common CDP, and so on).	", 
" 3. Migrated traces are output in CDP gathers if velocity analysis	",
"    is required, with dimension nxo*noff*nzo.  			", 
" 4. If the offset value of an input trace is not in the offset array 	",
"    of output, the nearest one in the array is chosen. 		",
" 5. Memory requirement for this program is about			",
"    	[ns*nxt*nzt+noff*nxo*nzo+4*nr*nzt+5*nxt*nzt+npa*(2*ns*nxt*nzt   ",
"	+noff*nxo*nzo+4*nxt*nzt)]*4 bytes				",
"    where nr = 1+min(nxt*dxt,0.5*offmax+aperx)/dxo. 			",
" 6. Amplitudes are computed using the reference velocity profile, v(z),",
"    specified by the parameters v0= and dvz=.				",
" 7. Input traces must specify source and receiver positions via the header",
"    fields tr.sx and tr.gx. Offset is computed automatically.		",
" 8. if limoff=0, input traces from outside the range defined by off0, doff, ",
"    noff, will get migrated into the extremal offset bins/planes.  E.g. if ",
"    absoff=0 and limoff=0, all traces with gx<sx will get migrated into the ",
"    off0 bin.",
"									",
NULL};
#endif

/*
 * Author:  Zhenyue Liu, 03/01/95,  Colorado School of Mines 
 * Modifcations:
 *    Gary Billings, Talisman Energy, Sept 2005:  added absoff, limoff.
 *
 *   Zhenyue Liu (1997). ”An analytical approach to migration 
 *   velocity analysis.” GEOPHYSICS, 62(4), 1238-1249.
 *     https://doi.org/10.1190/1.1444225
 *
 *
 * Trace header fields accessed: ns, dt, delrt, d2
 * Trace header fields modified: sx, gx
 */
 
/**************** end self doc ***********************************/


/* Library version of SUKDMIG2D
 *
 * The main program (the parameters, the files of traces and traveltime tables, the headers of the output traces) is left to the
 * caller. What is here are the three steps of the computation. The 2-D and 3-D arrays are flat, z the last (fast) index:
 *
 *	su_kdmig2d_reference:	the reference traveltime, slowness, cosine and angle tb, pb, cs0b, angb [nr][nzt] (timeb)
 *	su_kdmig2d_residual:	subtracts the reference traveltime from the traveltime tables ttab [ns][nxt][nzt] (resit)
 *	su_kdmig2d_trace:	migrates one trace, adding it to mig[nxo][nzo] (and mig1 for the velocity analysis, npv)
 *
 * Differences from the program:
 *  - The filter of the traces (filt), which kept its tables in static variables made at the first trace, makes them for each trace.
 *  - The work arrays of the amplitudes start at 0 (the program read what it had not set).
 *  - The checks of the parameters return a code.
 */

/* residual traveltime calculation based  on reference   time	*/
static void resit(int nx,float fx,float dx,int nz,int nr,float dr,
		float **tb,float **t,float x0)
{
	int ix,iz,jr;
	float xi,ar,sr,sr0;

	for(ix=0; ix<nx; ++ix){
		xi = fx+ix*dx-x0;
		ar = fabsf(xi)/dr;
		jr = (int)ar;
		sr = ar-jr;
		sr0 = 1.0-sr;
		if(jr>nr-2) jr = nr-2;
		for(iz=0; iz<nz; ++iz)
			t[ix][iz] -= sr0*tb[jr][iz]+sr*tb[jr+1][iz];
	}
}

/* sum of two tables	*/
static void sum2(int nx,int nz,float a1,float a2,float **t1,float **t2,float **t)
{
	int ix,iz;

	for(ix=0; ix<nx; ++ix)
		for(iz=0; iz<nz; ++iz)
			t[ix][iz] = a1*t1[ix][iz]+a2*t2[ix][iz];
}

/* compute  reference traveltime and slowness	*/
static void timeb(int nr,int nz,float dr,float dz,float fz,float a,
	float v0,float **t,float **p,float **cs0,float **ang)
{
	int  ir,iz;
	float r,z,v,rc,oa,temp,rou,zc;

	if( a==0.0) {
		for(ir=0,r=0;ir<nr;++ir,r+=dr)
			for(iz=0,z=fz;iz<nz;++iz,z+=dz){
				rou = sqrt(r*r+z*z);
				if(rou<dz) rou = dz;
				t[ir][iz] = rou/v0;
				p[ir][iz] = r/(rou*v0);
				cs0[ir][iz] = z/rou;
				ang[ir][iz] = asin(r/rou);
			}
	} else {
		oa = 1.0/a; 	zc = v0*oa;
		for(ir=0,r=0;ir<nr;++ir,r+=dr)
			for(iz=0,z=fz+zc;iz<nz;++iz,z+=dz){
				rou = sqrt(r*r+z*z);
				v = v0+a*(z-zc);
				if(ir==0){
					t[ir][iz] = log(v/v0)*oa;
					p[ir][iz] = 0.0;
					ang[ir][iz] = 0.0;
					cs0[ir][iz] = 1.0;
				} else {
					rc = (r*r+z*z-zc*zc)/(2.0*r);
					rou = sqrt(zc*zc+rc*rc);
					t[ir][iz] = log((v*(rou+rc))
						/(v0*(rou+rc-r)))*oa;
					p[ir][iz] = sqrt(rou*rou-rc*rc)
						/(rou*v0);
					temp = v*p[ir][iz];
					if(temp>1.0) temp = 1.0;
					ang[ir][iz] = asin(temp);
					cs0[ir][iz] = rc/rou;
				}
			}
	}
}

/* Low-pass filter, integration and phase shift for input data
   input:
    trace(nt)	single seismic trace
   fmax	high cut frequency
    ls		ls=1, line source; ls=0, point source
  output:
    trace(nt) 	filtered and phase-shifted seismic trace
    trf(nt+2m)	filtered, integrated and phase-shifted seismic trace, with m samples before and after
 */
static void filt(float *trace,int nt,float dt,float fmax,int ls,int m,float *trf)
{
	int nfft, itaper, nw, nwf;
	float *taper, *amp, *ampi, dw;
	int  it, iw, itemp;
	float temp, ftaper, const2, *rt;
	complex *ct;

	fmax *= 2.0*PI;
	ftaper = 0.1*fmax;
	const2 = sqrt(2.0);

	/* Set up FFT parameters */
	nfft = npfaro(nt+m, 2 * (nt+m));
	nw = nfft/2 + 1;
	dw = 2.0*PI/(nfft*dt);

	itaper = 0.5+ftaper/dw;
	taper = ealloc1float(2*itaper+1);
	for(iw=-itaper; iw<=itaper; ++iw){
		temp = (float)iw/(1.0+itaper);
		taper[iw+itaper] = (1-temp)*(1-temp)*(temp+2)/4;
	}

	nwf = 0.5+fmax/dw;
	if(nwf>nw-itaper-1) nwf = nw-itaper-1;
	amp = ealloc1float(nwf+itaper+1);
	ampi = ealloc1float(nwf+itaper+1);
	amp[0] = ampi[0] = 0.;
	for(iw=1; iw<=nwf+itaper; ++iw){
		amp[iw] = sqrt(dw*iw)/nfft;
		ampi[iw] = 0.5/(1-cos(iw*dw*dt));
	}

	/* Allocate fft arrays */
	rt   = ealloc1float(nfft);
	ct   = ealloc1complex(nw);

	memcpy(rt, trace, nt*FSIZE);
	memset((void *) (rt + nt), (int) '\0', (nfft-nt)*FSIZE);
	pfarc(1, nfft, rt, ct);

	for(iw=nwf-itaper;iw<=nwf+itaper;++iw){
		itemp = iw-(nwf-itaper);
		ct[iw] *= taper[itemp];
	}
	for(iw=nwf+itaper+1;iw<nw;++iw){
		ct[iw] = complex(0.0f,0.0f);
	}

	if(!ls){
		for(iw=0; iw<=nwf+itaper; ++iw){
			/* phase shifts PI/4 	*/
			float re = ct[iw].real(), im = ct[iw].imag();
			temp = (re-im)*amp[iw]*const2;
			ct[iw] = complex(temp, (re+im)*amp[iw]*const2);
		}
	} else {
		for(iw=0; iw<=nwf+itaper; ++iw){
			ct[iw] *= amp[iw];
		}
	}
	pfacr(-1, nfft, ct, rt);

	/* Load traces back in */
	for (it=0; it<nt; ++it) trace[it] = rt[it];

	/* Integrate traces   */
	for(iw=0; iw<=nwf+itaper; ++iw){
		ct[iw] *= ampi[iw];
	}
	pfacr(-1, nfft, ct, rt);
	for (it=0; it<m; ++it)  trf[it] = rt[nfft-m+it];
	for (it=0; it<nt+m; ++it)  trf[it+m] = rt[it];

	free1float(taper);
	free1float(amp);
	free1float(ampi);
	free1float(rt);
	free1complex(ct);
}

static void mig2d(float *trace,int nt,float ft,float dt,
	float sx,float gx,float **mig,float aperx,
  	int nx,float fx,float dx,float nz,float fz,float dz,
	int ls,int mtmax,float dxm,float fmax,float angmax,
	float **tb,float **pb,float **cs0b,float **angb,int nr,
	float **tsum,int nzt,float fzt,float dzt,int nxt,float fxt,float dxt,
	int npv,float **cssum,float **tvsum,float **mig1)
{
	int nxf,nxe,nxtf,nxte,ix,iz,iz0,izt0,nzp,jrs,jrg,jz,jt,mt,jx;
	float xm,x,dis,rxz,ar,srs,srg,srs0,srg0,sigp,z0,rdz,ampd,res0,
		angs,angg,cs0s,cs0g,ax,ax0,pmin,
		odt=1.0/dt,pd,az,sz,sz0,at,td,res,temp;
	float **tmt,**ampt,**ampti,**ampt1=NULL,*tm,*amp,*ampi,*amp1=NULL,
		*tzt,*trf,*zpt;

	tmt = alloc2float(nzt,nxt);
	ampt = alloc2float(nzt,nxt);
	ampti = alloc2float(nzt,nxt);
	tm = alloc1float(nzt);
	tzt = alloc1float(nzt);
	amp = alloc1float(nzt);
	ampi = alloc1float(nzt);
	zpt = alloc1float(nxt);
	trf = alloc1float(nt+2*mtmax);
	memset(tmt[0],0,sizeof(float)*(size_t)nxt*nzt);
	memset(ampt[0],0,sizeof(float)*(size_t)nxt*nzt);
	memset(ampti[0],0,sizeof(float)*(size_t)nxt*nzt);
	memset(tm,0,sizeof(float)*nzt);
	memset(tzt,0,sizeof(float)*nzt);
	memset(amp,0,sizeof(float)*nzt);
	memset(ampi,0,sizeof(float)*nzt);
	memset(zpt,0,sizeof(float)*nxt);
	memset(trf,0,sizeof(float)*(nt+2*mtmax));
	if(npv) {
		ampt1 = alloc2float(nzt,nxt);
		amp1 = alloc1float(nzt);
		memset(ampt1[0],0,sizeof(float)*(size_t)nxt*nzt);
		memset(amp1,0,sizeof(float)*nzt);
	}

	z0 = (fz-fzt)/dzt;
	rdz = dz/dzt;
	pmin = 1.0/(2.0*dxm*fmax);

	filt(trace,nt,dt,fmax,ls,mtmax,trf);

	xm = 0.5*(sx+gx);
	rxz = (angmax==90)?0.0:1.0/tan(angmax*PI/180.);
	nxtf = (xm-aperx-fxt)/dxt;
	if(nxtf<0) nxtf = 0;
	nxte = (xm+aperx-fxt)/dxt+1;
	if(nxte>=nxt) nxte = nxt-1;

	/* compute amplitudes and filter length	*/
	for(ix=nxtf; ix<=nxte; ++ix){
		x = fxt+ix*dxt;
		dis = (xm>=x)?xm-x:x-xm;
		izt0 = ((dis-dxt)*rxz-fzt)/dzt-1;
		if(izt0<0) izt0 = 0;
		if(izt0>=nzt) izt0 = nzt-1;

		ar = (sx>=x)?(sx-x)/dx:(x-sx)/dx;
		jrs = (int)ar;
		if(jrs>nr-2) jrs = nr-2;
		srs = ar-jrs;
		srs0 = 1.0-srs;
		ar = (gx>=x)?(gx-x)/dx:(x-gx)/dx;
		jrg = (int)ar;
		if(jrg>nr-2) jrg = nr-2;
		srg = ar-jrg;
		srg0 = 1.0-srg;
		sigp = ((sx-x)*(gx-x)>0)?1.0:-1.0;
		zpt[ix] = fzt+(nzt-1)*dzt;

		for(iz=izt0; iz<nzt; ++iz){
			angs = srs0*angb[jrs][iz]+srs*angb[jrs+1][iz];
			angg = srg0*angb[jrg][iz]+srg*angb[jrg+1][iz];
			cs0s = srs0*cs0b[jrs][iz]+srs*cs0b[jrs+1][iz];
			cs0g = srg0*cs0b[jrg][iz]+srg*cs0b[jrg+1][iz];
			ampd = (cs0s+cs0g)*cos(0.5*(angs-angg));
			if(ampd<0.0) ampd = -ampd;
			ampt[ix][iz] = ampd;

			pd = srs0*pb[jrs][iz]+srs*pb[jrs+1][iz]+sigp
			     *(srg0*pb[jrg][iz]+srg*pb[jrg+1][iz]);
			if(pd<0.0) pd = -pd;
			temp = pd*dxm*odt;
			if(temp<1) temp = 1.0;
			if(temp>mtmax) temp = mtmax;
			ampti[ix][iz] = ampd/(temp*temp);
			tmt[ix][iz] = temp;
			if(pd<pmin && zpt[ix]>fzt+(nzt-1.1)*dzt)
				zpt[ix] = fzt+iz*dzt;

			if(npv){
				if(cssum[ix][iz]<1.0)
					ampt1[ix][iz] = 0;
				else
					ampt1[ix][iz] = tvsum[ix][iz]/cssum[ix][iz];
			}
		}
	}

	nxf = (xm-aperx-fx)/dx+0.5;
	if(nxf<0) nxf = 0;
	nxe = (xm+aperx-fx)/dx+0.5;
	if(nxe>=nx) nxe = nx-1;

	/* interpolate amplitudes and filter length along lateral	*/
	for(ix=nxf; ix<=nxe; ++ix){
		x = fx+ix*dx;
		dis = (xm>=x)?xm-x:x-xm;
		izt0 = (dis*rxz-fzt)/dzt;
		if(izt0<0) izt0 = 0;
		if(izt0>=nzt) izt0 = nzt-1;
		iz0 = (dis*rxz-fz)/dz;
		if(iz0<0) iz0 = 0;
		if(iz0>=nz) iz0 = nz-1;

		ax = (x-fxt)/dxt;
		jx = (int)ax;
		ax = ax-jx;
		if(ax<=0.01) ax = 0.;
		if(ax>=0.99) ax = 1.0;
		ax0 = 1.0-ax;
		if(jx>nxte-1) jx = nxte-1;
		if(jx<nxtf) jx = nxtf;

		ar = (sx>=x)?(sx-x)/dx:(x-sx)/dx;
		jrs = (int)ar;
		if(jrs>nr-2) jrs = nr-2;
		srs = ar-jrs;
		srs0 = 1.0-srs;
		ar = (gx>=x)?(gx-x)/dx:(x-gx)/dx;
		jrg = (int)ar;
		if(jrg>nr-2) jrg = nr-2;
		srg = ar-jrg;
		srg0 = 1.0-srg;

		for(iz=izt0; iz<nzt; ++iz){
		    tzt[iz] = ax0*tsum[jx][iz]+ax*tsum[jx+1][iz]
				+srs0*tb[jrs][iz]+srs*tb[jrs+1][iz]
				+srg0*tb[jrg][iz]+srg*tb[jrg+1][iz];

		    amp[iz] = ax0*ampt[jx][iz]+ax*ampt[jx+1][iz];
		    ampi[iz] = ax0*ampti[jx][iz]+ax*ampti[jx+1][iz];
		    tm[iz] = ax0*tmt[jx][iz]+ax*tmt[jx+1][iz];

		    if(npv)
		    	amp1[iz] = ax0*ampt1[jx][iz]+ax*ampt1[jx+1][iz];
		}

		nzp = (ax0*zpt[jx]+ax*zpt[jx+1]-fz)/dz+1.5;
		if(nzp<iz0) nzp = iz0;
		if(nzp>nz) nzp = nz;

		/* interpolate along depth if operater aliasing 	*/
		for(iz=iz0; iz<nzp; ++iz) {
			az = z0+iz*rdz;
			jz = (int)az;
			if(jz>=nzt-1) jz = nzt-2;
			sz = az-jz;
			sz0 = 1.0-sz;
			td = sz0*tzt[jz]+sz*tzt[jz+1];
			at = (td-ft)*odt+mtmax;
			jt = (int)at;
			if(jt > mtmax && jt < nt+mtmax-1){
			    ampd = sz0*ampi[jz]+sz*ampi[jz+1];
			    mt = (int)(0.5+sz0*tm[jz]+sz*tm[jz+1]);
			    res = at-jt;
			    res0 = 1.0-res;
 			    temp = (res0*(-trf[jt-mt]+2.0*trf[jt]-trf[jt+mt])
				+res*(-trf[jt-mt+1]+2.0*trf[jt+1]
				-trf[jt+mt+1]))*ampd;
			    mig[ix][iz] += temp;

			    if(npv)
				mig1[ix][iz]  += temp
					*(sz0*amp1[jz]+sz*amp1[jz+1]);
			}
		}

		/* interpolate along depth if not operater aliasing 	*/
		for(iz=nzp; iz<nz; ++iz) {
			az = z0+iz*rdz;
			jz = (int)az;
			if(jz>=nzt-1) jz = nzt-2;
			sz = az-jz;
			sz0 = 1.0-sz;
			td = sz0*tzt[jz]+sz*tzt[jz+1];
			at = (td-ft)*odt;
			jt = (int)at;
			if(jt > 0 && jt < nt-1){
			    ampd = sz0*amp[jz]+sz*amp[jz+1];
			    res = at-jt;
			    res0 = 1.0-res;
 			    temp = (res0*trace[jt]+res*trace[jt+1])*ampd;
			    mig[ix][iz] += temp;
			    if(npv)
				mig1[ix][iz]  += temp
					*(sz0*amp1[jz]+sz*amp1[jz+1]);
			}
		}
	}

	free2float(ampt);
	free2float(ampti);
	free2float(tmt);
	free1float(amp);
	free1float(ampi);
	free1float(zpt);
	free1float(tm);
	free1float(tzt);
	free1float(trf);
	if(npv) {
		free1float(amp1);
		free2float(ampt1);
	}
}

/* the pointers to the rows of a flat array [n][m] */
static float **kd_rows(const float *base, int n, int m)
{
	int i;
	float **rows = (float**)ealloc1(n,sizeof(float*));
	for (i=0; i<n; ++i) rows[i] = (float*)base+(size_t)i*m;
	return rows;
}

void su_kdmig2d_reference(int nr, int nzt, float dxo, float dzt, float fzt, float dvz, float v0,
	float *tb, float *pb, float *cs0b, float *angb)
{
	float **t = kd_rows(tb,nr,nzt), **p = kd_rows(pb,nr,nzt), **cs = kd_rows(cs0b,nr,nzt), **an = kd_rows(angb,nr,nzt);
	timeb(nr,nzt,dxo,dzt,fzt,dvz,v0,t,p,cs,an);
	free1(t); free1(p); free1(cs); free1(an);
}

void su_kdmig2d_residual(int ns, float fs, float ds, int nxt, float fxt, float dxt, int nzt, int nr, float dxo,
	const float *tb, float *ttab)
{
	int is;
	float **tbr = kd_rows(tb,nr,nzt);
	for (is=0; is<ns; ++is) {
		float **t = kd_rows(ttab+(size_t)is*nxt*nzt,nxt,nzt);
		resit(nxt,fxt,dxt,nzt,nr,dxo,tbr,t,fs+is*ds);
		free1(t);
	}
	free1(tbr);
}

/* Migrates the trace data[nt] (which is not changed) with the shot at sx and the geophone at gx, adding to mig[nxo][nzo] (and
 * mig1[nxo][nzo] if npv, with the tables tv and cs[ns][nxt][nzt]). tsum, tt, tvsum, cssum are scratch [nxt][nzt].
 * Returns 0, 1 if the trace is outside of the range of the shots and the maximum offset (not migrated), or -3. */
int su_kdmig2d_trace(const float *data, int nt, float ft, float dt, float sx, float gx, float *mig, float aperx,
	int nxo, float fxo, float dxo, int nzo, float fzo, float dzo, int ls, int mtmax, float dxm, float fmax, float angmax,
	const float *tb, const float *pb, const float *cs0b, const float *angb, int nr,
	const float *ttab, int ns, float fs, float ds, float es, float offmax, float *tsum, float *tt,
	int nzt, float fzt, float dzt, int nxt, float fxt, float dxt,
	int npv, const float *tv, const float *cs, float *tvsum, float *cssum, float *mig1)
{
	float as,res;
	int is, status = 0;
	float **tbr, **pbr, **csr, **angr, **ts, **t2, **tr1, **tr2, **migr, **mig1r = NULL, **cssr = NULL, **tvsr = NULL;
	float *trace;

	if (nt<2 || dt<=0.0 || ns<2 || nr<2 || mtmax<1 || nxt<2 || nzt<2) return -3;
	if (!(MIN(sx,gx)>=fs && MAX(sx,gx)<=es && MAX(gx-sx,sx-gx)<=offmax)) return 1;

	trace = ealloc1float(nt);
	memcpy(trace,data,sizeof(float)*nt);
	tbr = kd_rows(tb,nr,nzt);
	pbr = kd_rows(pb,nr,nzt);
	csr = kd_rows(cs0b,nr,nzt);
	angr = kd_rows(angb,nr,nzt);
	ts = kd_rows(tsum,nxt,nzt);
	t2 = kd_rows(tt,nxt,nzt);
	migr = kd_rows(mig,nxo,nzo);
	if (npv) {
		mig1r = kd_rows(mig1,nxo,nzo);
		cssr = kd_rows(cssum,nxt,nzt);
		tvsr = kd_rows(tvsum,nxt,nzt);
	}

	as = (sx-fs)/ds;
	is = (int)as;
	if(is==ns-1) is=ns-2;
	res = as-is;
	if(res<=0.01) res = 0.0;
	if(res>=0.99) res = 1.0;
	tr1 = kd_rows(ttab+(size_t)is*nxt*nzt,nxt,nzt);
	tr2 = kd_rows(ttab+(size_t)(is+1)*nxt*nzt,nxt,nzt);
	sum2(nxt,nzt,1-res,res,tr1,tr2,ts);
	free1(tr1); free1(tr2);
	if(npv)  {
		tr1 = kd_rows(tv+(size_t)is*nxt*nzt,nxt,nzt);
		tr2 = kd_rows(tv+(size_t)(is+1)*nxt*nzt,nxt,nzt);
		sum2(nxt,nzt,1-res,res,tr1,tr2,tvsr);
		free1(tr1); free1(tr2);
		tr1 = kd_rows(cs+(size_t)is*nxt*nzt,nxt,nzt);
		tr2 = kd_rows(cs+(size_t)(is+1)*nxt*nzt,nxt,nzt);
		sum2(nxt,nzt,1-res,res,tr1,tr2,cssr);
		free1(tr1); free1(tr2);
	}

	as = (gx-fs)/ds;
	is = (int)as;
	if(is==ns-1) is=ns-2;
	res = as-is;
	if(res<=0.01) res = 0.0;
	if(res>=0.99) res = 1.0;
	tr1 = kd_rows(ttab+(size_t)is*nxt*nzt,nxt,nzt);
	tr2 = kd_rows(ttab+(size_t)(is+1)*nxt*nzt,nxt,nzt);
	sum2(nxt,nzt,1-res,res,tr1,tr2,t2);
	sum2(nxt,nzt,1,1,t2,ts,ts);
	free1(tr1); free1(tr2);
	if(npv)  {
		tr1 = kd_rows(tv+(size_t)is*nxt*nzt,nxt,nzt);
		tr2 = kd_rows(tv+(size_t)(is+1)*nxt*nzt,nxt,nzt);
		sum2(nxt,nzt,1-res,res,tr1,tr2,t2);
		sum2(nxt,nzt,1,1,t2,tvsr,tvsr);
		free1(tr1); free1(tr2);
		tr1 = kd_rows(cs+(size_t)is*nxt*nzt,nxt,nzt);
		tr2 = kd_rows(cs+(size_t)(is+1)*nxt*nzt,nxt,nzt);
		sum2(nxt,nzt,1-res,res,tr1,tr2,t2);
		sum2(nxt,nzt,1,1,t2,cssr,cssr);
		free1(tr1); free1(tr2);
	}

	mig2d(trace,nt,ft,dt,sx,gx,migr,aperx,
		nxo,fxo,dxo,nzo,fzo,dzo,
		ls,mtmax,dxm,fmax,angmax,
		tbr,pbr,csr,angr,nr,ts,nzt,fzt,dzt,nxt,fxt,dxt,
		npv,cssr,tvsr,mig1r);

	free1(tbr); free1(pbr); free1(csr); free1(angr); free1(ts); free1(t2); free1(migr);
	if (npv) { free1(mig1r); free1(cssr); free1(tvsr); }
	free1float(trace);
	return status;
}
