cwp_lib_src = [
    'abel.cpp',
    'airy.cpp',
    'alloc.cpp',
    'antialias.cpp',
    'axb.cpp',
    'bigmatrix.cpp',
    'butterworth.cpp',
    'conjugate_gradient.cpp',
    'convolution.cpp',
    'cubicspline.cpp',
    'dblas.cpp',
    'dge.cpp',
    'differentiate.cpp',
    'dpfafft.cpp',
    'exit.cpp',
    'frannor.cpp',
    'franuni.cpp',
    'hankel.cpp',
    'hartley.cpp',
    'hilbert.cpp',
    'holbergd1.cpp',
    'intcub.cpp',
    'intl2b.cpp',
    'intlin.cpp',
    'intlinc.cpp',
    'intlirr2b.cpp',
    'intsinc8.cpp',
    'inttable8.cpp',
    'linfit.cpp',
    'linregress.cpp',
    'maxmin.cpp',
    'mkdiff.cpp',
    'mkhdiff.cpp',
    'mksinc.cpp',
    'mnewt.cpp',
    'orthpolynomials.cpp',
    'pfafft.cpp',
    'polar.cpp',
    'printerplot.cpp',
    'quest.cpp',
    'ressinc8.cpp',
    'rfwtva.cpp',
    'rfwtvaint.cpp',
    'sblas.cpp',
    'scaxis.cpp',
    'sge.cpp',
    'shfs8r.cpp',
    'sinc.cpp',
    'sort.cpp',
    'sqr.cpp',
    'stoep.cpp',
    'strstuff.cpp',
    'svd.cpp',
    'swapbyte.cpp',
    'symmeigen.cpp',
    'tempname.cpp',
    'tridiagonal.cpp',
    'unwrapphase.cpp',
    'vandermonde.cpp',
    'waveforms.cpp',
    'windows.cpp',
    'wrap.cpp',
    'xcor.cpp',
    'xindex.cpp',
    'yclip.cpp',
    'yxtoxy.cpp',
    'zasc.cpp',
    'zebc.cpp',
]

cwp_lib = library(
    'cwp',
    cwp_lib_src,
    include_directories: cwp_include_dir
)

su_cwp_dep = declare_dependency(
    include_directories: cwp_include_dir,
    link_with: cwp_lib
)