su_lib_srcs = files(
    'bilinear.cpp',
    'elco_scalar.cpp',
    'fgetgthr.cpp',
    'fgethdr.cpp',
    'fgettr.cpp',
    'fputgthr.cpp',
    'fputtr.cpp',
    'getSPSfield.cpp',
    'gridread.cpp',
    'gridxy.cpp',
    'hdrpkge.cpp',
    'headcase.cpp',
    'linterpd.cpp',
    'qdefine.cpp',
    'readkfile.cpp',
    'tabplot.cpp',
    'valpkge.cpp',
)